### ISSUE TITLE
[bug] Wrong Keyboard Event on Command Palette 

### ISSUE THREAD

**Issue by mariio46** [irsyadadl/d.#28]
Command Palette should use `ctrl/cmd + k` but it actually use only `k` to open the Command Palette

maybe you should add the second condition on `command-palette.tsx`
```tsx
const down = (e: KeyboardEvent) => {
  if (e.key === 'k' && (e.metaKey || e.ctrlKey)) {
    e.preventDefault()
    // @ts-ignore
    setOpen((open: boolean) => !open)
  }
}
```

**Comment by irsyadadl** [comment]
Thanks for the heads up. We'll patch it in the next update.
